name: empty
description: Empty is an esoteric language designed to convert a sequence of keywords into a pure alphabetic sentence.
version: 1.0.0

dependencies: {
  chalkdart: ^2.0.8
}

environment:
  sdk: '>=2.18.4 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
